### ISSUE TITLE
zoe obd

### ISSUE THREAD

**Issue by Fatih0** [rand12345/Zoe-PH1-EV-CAN-data#1]
do you have zoe2 obd2 can datas

**Comment by f0ld** [comment]
> do you have zoe2 obd2 can datas

Zoe Ph.2 uses something called a "secured gateway". This means you will get only limited diagnostic data over the obd port using Iso-TP style messages as the gateway prevents you from getting direct access to the Controll Units (if you dont have an access key from renault). 
If you intend to message ecus via can on a ph.2 Zoe it is better to directly wire into the canbus behind it (that does mean different can-ids though). If you intend to only use diagnostic data via the obd port a great resource is the CanZE Repository. There you will find all the data you need.
Or are you looking for actual logs of can traffic?

I am not entirely sure if that is what you asked for since your request is very short and lacks significant details...

**Comment by rand12345** [comment]
> do you have zoe2 obd2 can datas

You can find that information here.

https://github.com/ljames28/Renault-Zoe-PH2-ZE50-Canbus-LBC-Information
